function [filenames, unique_im_nrs] = vcd_getOBJfilenames()

% 65-80 are core images (the same as params.stim.obj.unique_im_nrs_core)
% 367:430 are wm test images (the same as params.stim.obj.unique_im_nrs_wm_test)
unique_im_nrs = [65:80,239:302]';

filenames = {'faces_damonwayans_rot31.png'; ...
            'faces_lisa_rot21.png'; ...
            'faces_sophia_rot76.png'; ...
            'animals_parrot_rot16.png'; ...
            'animals_cat_rot51.png'; ...
            'animals_bear_rot66.png'; ...
            'animals_giraffe_rot41.png'; ...
            'tools_drill_rot11.png'; ...
            'tools_brush_rot06.png'; ...
            'vehicles_bus_rot36.png'; ...
            'vehicles_suv_rot61.png'; ...
            'food_pizza_rot86.png'; ...
            'food_banana_rot56.png'; ...
            'places_gothicchurch_rot81.png'; ...
            'places_house1_rot26.png'; ...
            'places_watertower_rot71.png'; ...
            'faces_damonwayans_rot27.png'; ...
            'faces_damonwayans_rot29.png'; ...
            'faces_damonwayans_rot33.png'; ...
            'faces_damonwayans_rot35.png'; ...
            'faces_lisa_rot17.png'; ...
            'faces_lisa_rot19.png'; ...
            'faces_lisa_rot23.png'; ...
            'faces_lisa_rot25.png'; ...
            'faces_sophia_rot72.png'; ...
            'faces_sophia_rot74.png'; ...
            'faces_sophia_rot78.png'; ...
            'faces_sophia_rot80.png'; ...
            'animals_parrot_rot12.png'; ...
            'animals_parrot_rot14.png'; ...
            'animals_parrot_rot18.png'; ...
            'animals_parrot_rot20.png'; ...
            'animals_cat_rot47.png'; ...
            'animals_cat_rot49.png'; ...
            'animals_cat_rot53.png'; ...
            'animals_cat_rot55.png'; ...
            'animals_bear_rot62.png'; ...
            'animals_bear_rot64.png'; ...
            'animals_bear_rot68.png'; ...
            'animals_bear_rot70.png'; ...
            'animals_giraffe_rot37.png'; ...
            'animals_giraffe_rot39.png'; ...
            'animals_giraffe_rot43.png'; ...
            'animals_giraffe_rot45.png'; ...
            'tools_drill_rot07.png'; ...
            'tools_drill_rot09.png'; ...
            'tools_drill_rot13.png'; ...
            'tools_drill_rot15.png'; ...
            'tools_brush_rot02.png'; ...
            'tools_brush_rot04.png'; ...
            'tools_brush_rot08.png'; ...
            'tools_brush_rot10.png'; ...
            'vehicles_bus_rot32.png'; ...
            'vehicles_bus_rot34.png'; ...
            'vehicles_bus_rot38.png'; ...
            'vehicles_bus_rot40.png'; ...
            'vehicles_suv_rot57.png'; ...
            'vehicles_suv_rot59.png'; ...
            'vehicles_suv_rot63.png'; ...
            'vehicles_suv_rot65.png'; ...
            'food_pizza_rot82.png'; ...
            'food_pizza_rot84.png'; ...
            'food_pizza_rot88.png'; ...
            'food_pizza_rot90.png'; ...
            'food_banana_rot52.png'; ...
            'food_banana_rot54.png'; ...
            'food_banana_rot58.png'; ...
            'food_banana_rot60.png'; ...
            'places_gothicchurch_rot77.png'; ...
            'places_gothicchurch_rot79.png'; ...
            'places_gothicchurch_rot83.png'; ...
            'places_gothicchurch_rot85.png'; ...
            'places_house1_rot22.png'; ...
            'places_house1_rot24.png'; ...
            'places_house1_rot28.png'; ...
            'places_house1_rot30.png'; ...
            'places_watertower_rot67.png'; ...
            'places_watertower_rot69.png'; ...
            'places_watertower_rot73.png'; ...
            'places_watertower_rot75.png'};
        
assert(isequal(length(filenames),length(unique_im_nrs)));
        
return