function makeprettyfigures()

% general graphics, this will apply to any figure you open
% (groot is the default figure object).
set(groot, ...
'DefaultFigureColor', 'w', ...
'DefaultAxesLineWidth', 0.5, ...
'DefaultAxesXColor', 'k', ...
'DefaultAxesYColor', 'k', ...
'DefaultAxesFontSize', 15, ...
'DefaultAxesFontName', 'Mukti Narrow', ... 'Helvetica',
'DefaultLineLineWidth', 1.5, ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextFontSize', 15, ...
'DefaultTextFontName', 'Mukti Narrow', ... 'Helvetica',
'DefaultAxesBox', 'off', ...
'DefaultAxesTickLength', [0.02 0.025], ...
'DefaultAxesTickDir', 'out', ...
'DefaultAxesTickDirMode', 'manual', ...
'DefaultAxesTitleFontWeight','normal',...
'DefaultAxesFontUnits', 'points'); %, ...

return